# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose the default port
EXPOSE 3000

# Start the server in CLI mode so that it communicates via stdio without extra non-JSON logs
CMD [ "npm", "run", "start:cli" ]
